name: Deploy AWS Amplify App

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Amplify App ID'
        required: true
        type: string
      branch_name:
        description: 'Branch Name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Amplify App
        run: |
          aws amplify start-job \
            --app-id "${{ github.event.inputs.app_id }}" \
            --branch-name "${{ github.event.inputs.branch_name }}" \
            --job-type RELEASE