buildSpec: version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing dependencies..."
        - npm cd --cache .npm --prefer-offline
    build:
      commands:
        - echo "Building the application..."
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - .npm/**/*