name: Create Amplify App via Shared CDK

on:
  workflow_dispatch:
    inputs:
      cdk_repo:
        description: 'GitHub repo (owner/repo) containing the shared CDK code'
        required: true
        default: 'bsnyder74/cdk'
        type: string
      cdk_ref:
        description: 'Git ref (branch/tag/SHA) for the CDK repo'
        required: false
        default: 'main'
        type: string
      cdk_project_path:
        description: 'Path to the CDK project in the shared repo (e.g., amplify/sbt-amplify-app)'
        required: true
        type: string
      env_file:
        description: 'Path to .env file in the Amplify app repo (e.g., .env/prod.env)'
        required: true
        type: string
      cdk_stack_name:
        description: 'Name of the CDK stack to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Amplify App Repo (Calling Repo)
        uses: actions/checkout@v4
        with:
          # path: amplify-app
          path: ${{ github.repository.name }}

      - name: Verify paths
        run: |
          echo "Checked out Repo: ${{ github.repository.name }}"
          echo "Current Directory: $(pwd)"
          echo "Contents:"
          ls -la

      - name: Checkout Shared CDK Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.cdk_repo }}
          ref: ${{ github.event.inputs.cdk_ref }}
          path: cdk

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install CDK dependencies
        run: |
          cd cdk/${{ github.event.inputs.cdk_project_path }}
          npm ci

      - name: Copy .env file to CDK project
        run: |
          mkdir -p cdk/amplify/sbt-amplify-app/env
          pwd
          ls -la
          cp ${{ github.event.inputs.env_file }} cdk/${{ github.event.inputs.cdk_project_path }}/env/deploy.env

      - name: Deploy Amplify App via CDK
        env:
          DOTENV_FILE: env/deploy.env
        run: |
          pwd
          ls -la
          cd cdk/${{ github.event.inputs.cdk_project_path }}
          pwd
          ls -la
          npx cdk deploy ${{ github.event.inputs.cdk_stack_name }} --require-approval never
